//-- AT Media 1.0.001 -- Copyright 2009 AT INTERNET, All Rights Reserved.
//-- (to be used with AT Tag 3.4.002 or later)
if(!document.getElementById&&document.all){document.getElementById=function(id){return document.all[id];}}
if(typeof ATMedia=='undefined'){var ATMedia={};}
ATMedia.init=function(){for(var i=0;i<arguments.length;i++){var medias=document.getElementsByTagName(arguments[i]);for(var j=0;j<medias.length;j++){if(medias[j].getAttribute('xttype')){ATMedia.MediaControl.controls.push(new ATMedia.MediaControl(medias[j]));}}}}
ATMedia.MediaControl=function(media){if(typeof media=='String'){media=document.getElementById(media);}this.media=media;this.media.oldState='ended';this.media.newState='ended';this.media.rmp=0;this.media.rmpf=0;this.media.rmbufp=0;this.media.action=null;this.media.hit=function(){if(this.action!=null){var xttype=this.getAttribute('xttype');xttype+=(this.getAttribute('xtplayer')!=null)?'&plyr='+this.getAttribute('xtplayer'):'';var xtn2=this.getAttribute('xtn2');if(typeof(TVRubrik)!='undefined'){var BeforeName=TVRubrik+"::";}else{var BeforeName="";}var xtrichname=BeforeName+this.getAttribute('xtrichname');xtrichname+=(this.getAttribute('xtclink')!=null)?'&clnk='+this.getAttribute('xtclink'):'';var xtaction=this.action;var xtcustom=this.getAttribute('xtcustom');var xtrefresh=this.getAttribute('xtrefresh');var xtduration=this.getAttribute('xtduration');this.rmp=Math.round(this.currentTime);this.rmp=(this.rmp<0)?0:this.rmp;this.rmp=(this.rmp>parseInt(this.getAttribute('xtduration'),10))?parseInt(this.getAttribute('xtduration'),10):this.rmp;var xtrmp='&rmp='+this.rmp+'&rmpf='+this.rmpf+'&rmbufp='+this.rmbufp;var xtquality=this.getAttribute('xtquality');var xtstream=this.getAttribute('xtstream');var xtlocation=this.getAttribute('xtlocation');var xtmode=this.getAttribute('xtmode');var xtsize=this.getAttribute('xtsize');var xtextension=this.getAttribute('xtextension');xt_rm(xttype,xtn2,xtrichname,xtaction,xtcustom,xtrefresh,xtduration,xtrmp,xtquality,xtstream,xtlocation,xtmode,xtsize,xtextension);this.action=null;}};if((typeof HTMLMediaElement!='undefined')&&(this.media instanceof HTMLMediaElement)){this.addListeners();}}
ATMedia.MediaControl.controls=[];
ATMedia.MediaControl.prototype.addListeners=function(){var obj=this;var events=['playing','pause','ended'];for(var i=0;i<events.length;i++){if(window.addEventListener){obj.media.addEventListener(events[i],obj.fire,false);}else if(window.attachEvent){obj.media.attachEvent('on'+events[i],obj.fire);}}if(window.addEventListener){obj.media.addEventListener('progress',obj.progress,false);obj.media.addEventListener('seeked',obj.seek,false);}else if(window.attachEvent){obj.media.attachEvent('onprogress',obj.progress);obj.media.attachEvent('onseeked',obj.seek);}}
ATMedia.MediaControl.prototype.fire=function(e){var obj=this;var readyState=obj.readyState;var networkState=obj.networkState;if(networkState<2||readyState<1){return;}obj.oldState=obj.newState;obj.newState=e.type;if((readyState<4)&&(obj.newState=='playing')&&(obj.oldState!='buffering')){obj.newState='buffering';}switch(obj.newState+obj.oldState){case 'bufferingended':case 'bufferingpause':obj.action='play&buf=1';break;case "playingended":case "playingpause":obj.action='play';break;case'playingbuffering':obj.action='info';break;case'bufferingplaying':obj.action='info&buf=1';break;case'pauseplaying':case'pausebuffering':obj.action='pause';break;case'endedplaying':case'endedpause':case'endedbuffering':obj.action='stop';break;default:break;}obj.rmpf=0;obj.hit();}
ATMedia.MediaControl.prototype.progress=function(e){var obj=this;if(e.total==0)obj.rmbufp=0;else obj.rmbufp=Math.floor((e.loaded/e.total)*parseInt(obj.getAttribute('xtduration'),10));obj.rmbufp=isNaN(obj.rmbufp)?0:obj.rmbufp;obj.rmbufp=(obj.rmbufp>parseInt(obj.getAttribute('xtduration'),10))?parseInt(obj.getAttribute('xtduration'),10):obj.rmbufp;}
ATMedia.MediaControl.prototype.seek=function(e){var obj=this;obj.rmpf=obj.rmp;obj.action='move';obj.hit();}
$(document).ready(function(){ ATMedia.init('VIDEO','AUDIO'); });
